server:
  port: 8080
okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
spring:
   application:
      name: post-service
   cloud:
      stream:
         function:
           definition: postSupplier
         bindings:
           postSupplier-out-0:
             destination: post-event
         kafka:
           bindings:
             postSupplier-out-0:
               producer:
                 configuration:
                   value:
                     serializer: org.apache.kafka.common.serialization.ByteArraySerializer
   data:
      mongodb: 
         database: ${MONGO_DB_NAME}
         host: ${MONGO_HOST}
         port: ${MONGO_PORT}
   security:
      oauth2:
         resourceserver:
           jwt:
             issuer: ${OKTA_ISSUER}
             client-id: ${CLIENT_ID}
             client-secret: ${CLIENT_SECRET}
   
             